package com.github.panpf.sketch.ability

const val PROGRESS_INDICATOR_STEP_ANIMATION_DURATION: Int = 150
const val PROGRESS_INDICATOR_HIDDEN_WHEN_INDETERMINATE: Boolean = false
const val PROGRESS_INDICATOR_HIDDEN_WHEN_COMPLETED: Boolean = true

const val PROGRESS_INDICATOR_MASK_COLOR: Int = 0x22000000

const val PROGRESS_INDICATOR_RING_COLOR: Int = 0xFFFFFFFF.toInt()
const val PROGRESS_INDICATOR_BACKGROUND_ALPHA_PERCENT: Float = 0.25f
const val PROGRESS_INDICATOR_RING_SIZE: Float = 50f
const val PROGRESS_INDICATOR_RING_WIDTH_PERCENT: Float = 0.1f

const val PROGRESS_INDICATOR_SECTOR_SIZE: Float = 50f
const val PROGRESS_INDICATOR_SECTOR_BACKGROUND_COLOR: Int = 0x44000000
const val PROGRESS_INDICATOR_SECTOR_PROGRESS_COLOR: Int = 0xFFFFFFFF.toInt()
const val PROGRESS_INDICATOR_SECTOR_STROKE_COLOR: Int = 0xFFFFFFFF.toInt()
const val PROGRESS_INDICATOR_SECTOR_STROKE_WIDTH_PERCENT: Float = 0.02f