name: Deploy API Docs

on: workflow_dispatch

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: zulu

jobs:
  deploy-api-docs:
    name: Deploy API Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        continue-on-error: true
        timeout-minutes: 5
        with:
          cache-overwrite-existing: true

      - name: Build the API docs
        run: ./gradlew dokkaGenerate

      - name: Check out the gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages

      - name: Remove old api directory
        run: rm -rf api/*

      - name: Create api directory
        run: mkdir -p api

      - name: Move build artifacts to api directory
        run: mv build/dokka/html/* api/

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "Update api docs"
          branch: gh-pages
          file_pattern: api/*