name: Publish To Maven Central

on: workflow_dispatch

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: zulu

jobs:
  publish:
    name: Publish To Maven Central
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        continue-on-error: true
        timeout-minutes: 5
        with:
          cache-overwrite-existing: true

      - name: Setup Android
        uses: android-actions/setup-android@v4
        with:
          packages: 'platform-tools'

      - name: Run publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache