name: Test JVM

on: workflow_dispatch

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: zulu

jobs:
  test-jvm-linux:
    name: Test JVM Linux
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        continue-on-error: true
        timeout-minutes: 5
        with:
          cache-overwrite-existing: true

      - name: Run jvm test
        run: internal/test_jvm.sh

  test-jvm-macos:
    name: Test JVM macOS
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        continue-on-error: true
        timeout-minutes: 5
        with:
          cache-overwrite-existing: true

      - name: Run jvm test
        run: internal/test_jvm.sh

  test-jvm-windows:
    name: Test JVM Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        continue-on-error: true
        timeout-minutes: 5
        with:
          cache-overwrite-existing: true

      - name: Run jvm test
        run: ./gradlew desktopTest --continue